{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "923a716e-0283-434c-9641-ae2a32464be6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "def augment_image(image_path, save_dir):\n",
    "    \"\"\"\n",
    "    Function: Implement multi-dimensional data augmentation based on ResNet paper's preprocessing specifications\n",
    "    Core Logic: Refer to the augmentation strategy in the paper [5-60] to avoid feature distortion caused by excessive augmentation\n",
    "    \"\"\"\n",
    "    # Read image and convert to RGB (OpenCV defaults to BGR, adapting to subsequent visualization and model input)\n",
    "    img = cv2.imread(image_path)\n",
    "    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "    img_name = image_path.split(\"/\")[-1].split(\".\")[0]\n",
    "    \n",
    "    # 1. Rotate 15° (the paper does not specify a specific angle; ±15° is chosen to balance diversity and feature retention)\n",
    "    h, w = img_rgb.shape[:2]\n",
    "    M_rot = cv2.getRotationMatrix2D((w//2, h//2), 15, 1)\n",
    "    img_rot = cv2.warpAffine(img_rgb, M_rot, (w, h))\n",
    "    \n",
    "    # 2. Horizontal flipping (core augmentation method in ResNet paper's ImageNet experiments, forcing key feature retention)\n",
    "    img_flip = cv2.flip(img_rgb, 1)\n",
    "    \n",
    "    # 3. Brightness adjustment (±20%, referring to the paper's \"moderate augmentation\" principle to avoid skin texture distortion)\n",
    "    img_hsv = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2HSV)\n",
    "    img_hsv[:, :, 2] = np.clip(img_hsv[:, :, 2] * 1.2, 0, 255)  # Brightness +20%\n",
    "    img_bright = cv2.cvtColor(img_hsv, cv2.COLOR_HSV2RGB)\n",
    "    \n",
    "    # Uniformly scale to 224×224 (ResNet paper's input size, adapting to the MBConv module of EfficientNet)\n",
    "    aug_imgs = [img_rot, img_flip, img_bright]\n",
    "    aug_names = [\"_rot15\", \"_flip\", \"_bright120\"]\n",
    "    for idx, (aug_img, aug_name) in enumerate(zip(aug_imgs, aug_names)):\n",
    "        img_resized = cv2.resize(aug_img, (224, 224))\n",
    "        save_path = f\"{save_dir}/{img_name}{aug_name}.jpg\"\n",
    "        cv2.imwrite(save_path, cv2.cvtColor(img_resized, cv2.COLOR_RGB2BGR))\n",
    "    \n",
    "    return f\"Successfully generated 3 augmented samples for {img_name}, complying with ResNet preprocessing specifications\"\n",
    "\n",
    "# Call the function (taking FaceForensics++ real samples as an example)\n",
    "result = augment_image(\n",
    "    image_path=\"data/raw/real/001.jpg\",\n",
    "    save_dir=\"data/processed/augmented/real\"\n",
    ")\n",
    "print(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f760047b-576f-4a27-bb6d-5dc10706977f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def crop_face_from_video(video_path, save_dir, frame_interval=10):\n",
    "    \"\"\"\n",
    "    Function: Extract frames from Deepfake videos and crop faces, focusing on key detection regions\n",
    "    Core Logic: Draw on the padding strategy in ResNet paper [5-111] to ensure the integrity of face features\n",
    "    \"\"\"\n",
    "    # Load OpenCV pre-trained Haar cascade classifier (lightweight, adapting to laptop CPU)\n",
    "    face_cascade = cv2.CascadeClassifier(\n",
    "        cv2.data.haarcascades + \"haarcascade_frontalface_default.xml\"\n",
    "    )\n",
    "    cap = cv2.VideoCapture(video_path)\n",
    "    frame_count = 0\n",
    "    face_count = 0\n",
    "    video_name = video_path.split(\"/\")[-1].split(\".\")[0]\n",
    "    \n",
    "    while cap.isOpened():\n",
    "        ret, frame = cap.read()\n",
    "        if not ret:\n",
    "            break\n",
    "        \n",
    "        # Extract 1 frame every 10 frames (balancing data volume and processing efficiency, adapting to lightweight requirements)\n",
    "        if frame_count % frame_interval == 0:\n",
    "            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "            gray = cv2.cvtColor(frame_rgb, cv2.COLOR_RGB2GRAY)\n",
    "            faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)\n",
    "            \n",
    "            # Only retain frames with a single face (avoiding multi-face interference, focusing on Deepfake's core forgery region)\n",
    "            if len(faces) == 1:\n",
    "                x, y, w, h = faces[0]\n",
    "                # Padding strategy: Expand the region by 10%, referring to the ResNet paper's principle of \"completely retaining features\"\n",
    "                pad = int(min(w, h) * 0.1)\n",
    "                x_pad = max(0, x - pad)\n",
    "                y_pad = max(0, y - pad)\n",
    "                w_pad = min(frame_rgb.shape[1] - x_pad, w + 2*pad)\n",
    "                h_pad = min(frame_rgb.shape[0] - y_pad, h + 2*pad)\n",
    "                face_img = frame_rgb[y_pad:y_pad+h_pad, x_pad:x_pad+w_pad]\n",
    "                \n",
    "                # Uniformly scale to 224×224, consistent with data augmentation output\n",
    "                face_resized = cv2.resize(face_img, (224, 224))\n",
    "                save_path = f\"{save_dir}/{video_name}_face{face_count}.jpg\"\n",
    "                cv2.imwrite(save_path, cv2.cvtColor(face_resized, cv2.COLOR_RGB2BGR))\n",
    "                face_count += 1\n",
    "        \n",
    "        frame_count += 1\n",
    "    \n",
    "    cap.release()\n",
    "    return f\"Video {video_name} processed successfully, generating {face_count} standardized face images\"\n",
    "\n",
    "# Call the function (taking FaceForensics++ fake videos as an example)\n",
    "crop_result = crop_face_from_video(\n",
    "    video_path=\"data/raw/fake/001.mp4\",\n",
    "    save_dir=\"data/processed/faces/fake\"\n",
    ")\n",
    "print(crop_result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "632cbb97-90ce-42fe-a50c-90ca1821baa6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "def create_dataset_label(root_dir, save_csv_path):\n",
    "    \"\"\"\n",
    "    Function: Generate standardized label tables and divide training/test sets\n",
    "    Core Logic: Refer to the dataset division specifications in ResNet paper [5-64] to ensure label balance\n",
    "    \"\"\"\n",
    "    # Collect data paths and labels (0=real, 1=fake, meeting the needs of binary classification tasks)\n",
    "    data = []\n",
    "    for label, folder in enumerate([\"real\", \"fake\"]):\n",
    "        folder_path = os.path.join(root_dir, folder)\n",
    "        for img_name in os.listdir(folder_path):\n",
    "            if img_name.endswith(\".jpg\"):\n",
    "                img_path = os.path.join(folder_path, img_name)\n",
    "                # Record key information, referring to the ResNet paper's \"data traceability\" principle\n",
    "                data.append({\n",
    "                    \"image_path\": img_path,\n",
    "                    \"label\": label,\n",
    "                    \"data_source\": \"FaceForensics++\",\n",
    "                    \"image_size\": \"224×224\",\n",
    "                    \"augmentation_type\": img_name.split(\"_\")[-1].split(\".\")[0]  # Mark augmentation type\n",
    "                })\n",
    "    \n",
    "    # Generate total label table for subsequent tracing and management\n",
    "    df = pd.DataFrame(data)\n",
    "    df.to_csv(save_csv_path, index=False, encoding=\"utf-8\")\n",
    "    total_real = len(df[df[\"label\"] == 0])\n",
    "    total_fake = len(df[df[\"label\"] == 1])\n",
    "    print(f\"Total label table generated: {len(df)} data entries (real: {total_real} entries, fake: {total_fake} entries)\")\n",
    "    \n",
    "    # Divide into training/test sets at 8:2 ratio, stratify parameter ensures balanced label distribution (referring to ResNet paper's balance principle)\n",
    "    train_df, test_df = train_test_split(\n",
    "        df, test_size=0.2, random_state=42, stratify=df[\"label\"]\n",
    "    )\n",
    "    train_df.to_csv(\"labels/train_labels.csv\", index=False, encoding=\"utf-8\")\n",
    "    test_df.to_csv(\"labels/test_labels.csv\", index=False, encoding=\"utf-8\")\n",
    "    \n",
    "    # Verify label distribution\n",
    "    train_real = len(train_df[train_df[\"label\"] == 0])\n",
    "    train_fake = len(train_df[train_df[\"label\"] == 1])\n",
    "    test_real = len(test_df[test_df[\"label\"] == 0])\n",
    "    test_fake = len(test_df[test_df[\"label\"] == 1])\n",
    "    print(f\"Training set: {len(train_df)} entries (real: {train_real} entries, fake: {train_fake} entries)\")\n",
    "    print(f\"Test set: {len(test_df)} entries (real: {test_real} entries, fake: {test_fake} entries)\")\n",
    "    \n",
    "    return \"Label table generation and division completed, complying with ResNet dataset management specifications\"\n",
    "\n",
    "# Call the function (root directory contains real/fake subfolders)\n",
    "label_result = create_dataset_label(\n",
    "    root_dir=\"data/processed\",\n",
    "    save_csv_path=\"labels/total_labels.csv\"\n",
    ")\n",
    "print(label_result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "edb73bea-5799-4b02-b880-f3adeb7db734",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "from tensorflow.keras import layers, models\n",
    "\n",
    "def tensor_basics_demo():\n",
    "    \"\"\"\n",
    "    Function: Demonstrate core TensorFlow operations, adapting to CNN input requirements\n",
    "    Core Logic: Refer to the feature map operation logic in ResNet paper [5-42]\n",
    "    \"\"\"\n",
    "    # Simulate preprocessed image tensor (batch_size=2, height=224, width=224, channels=3)\n",
    "    img_tensor = tf.random.normal(shape=(2, 224, 224, 3))\n",
    "    print(\"1. Shape of simulated image tensor (adapting to CNN input):\", img_tensor.shape)  # Output: (2, 224, 224, 3)\n",
    "    \n",
    "    # Pooling operation (used in ResNet paper to halve feature map size while retaining key features)\n",
    "    pooled_tensor = layers.MaxPooling2D(pool_size=(2, 2))(img_tensor)\n",
    "    print(\"2. Shape of pooled tensor (size halved):\", pooled_tensor.shape)  # Output: (2, 112, 112, 3)\n",
    "    \n",
    "    return img_tensor, pooled_tensor\n",
    "\n",
    "def simple_residual_block(input_tensor, filters=32):\n",
    "    \"\"\"\n",
    "    Function: Implement a simplified residual block, drawing on the y=F(x)+x logic in ResNet paper [5-43]\n",
    "    Core Structure: Convolution → BN → ReLU → Convolution → BN → Shortcut Addition → ReLU\n",
    "    \"\"\"\n",
    "    # Residual mapping F(x): Refer to the ResNet paper's layer order design of \"convolution → BN → activation\"\n",
    "    x = layers.Conv2D(filters, (3, 3), padding=\"same\")(input_tensor)\n",
    "    x = layers.BatchNormalization()(x)  # BN layer follows convolution closely to improve convergence stability (paper [5-60])\n",
    "    x = layers.ReLU()(x)\n",
    "    \n",
    "    x = layers.Conv2D(filters, (3, 3), padding=\"same\")(x)\n",
    "    x = layers.BatchNormalization()(x)\n",
    "    \n",
    "    # Shortcut connection: Direct addition when dimensions are consistent; 1×1 convolution projection when dimensions are inconsistent (paper [5-47])\n",
    "    if input_tensor.shape[-1] == x.shape[-1]:\n",
    "        output_tensor = layers.Add()([x, input_tensor])\n",
    "    else:\n",
    "        input_proj = layers.Conv2D(filters, (1, 1), padding=\"same\")(input_tensor)\n",
    "        output_tensor = layers.Add()([x, input_proj])\n",
    "    \n",
    "    output_tensor = layers.ReLU()(output_tensor)\n",
    "    return output_tensor\n",
    "\n",
    "# Call the function for verification\n",
    "tensor_basics_demo()\n",
    "# Test the residual block (input is a 224×224 image tensor)\n",
    "input_tensor = tf.random.normal(shape=(2, 224, 224, 3))\n",
    "res_block_output = simple_residual_block(input_tensor, filters=32)\n",
    "print(\"3. Shape of residual block output tensor:\", res_block_output.shape)  # Output: (2, 224, 224, 32)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-panel-2023.05-py310",
   "language": "python",
   "name": "conda-env-anaconda-panel-2023.05-py310-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
